# Generated by Django 3.0.7 on 2020-09-14 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mycloud', '0007_document_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='user',
            new_name='user_id',
        ),
    ]
