# Generated by Django 3.0.7 on 2020-09-14 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mycloud', '0009_auto_20200914_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='user_id',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
