# Generated by Django 3.0.7 on 2020-09-15 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mycloud', '0014_auto_20200915_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='user_id',
            new_name='user',
        ),
    ]
