# Generated by Django 3.0.7 on 2020-09-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mycloud', '0019_auto_20200921_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=21)),
                ('image', models.ImageField(upload_to='documents/%y%m%d')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
